// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'autoplay': string;
  'cardRow': string;
  'game': string;
}
export const cssExports: CssExports;
export default cssExports;
