// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'GameControls': string;
  'level': string;
  'right': string;
  'screen': string;
  'timer': string;
}
export const cssExports: CssExports;
export default cssExports;
