// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'current': string;
  'header': string;
  'player': string;
  'rating': string;
}
export const cssExports: CssExports;
export default cssExports;
