// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backwardButton': string;
  'current': string;
  'forwardButton': string;
  'table': string;
  'tableFooter': string;
  'tableHeader': string;
  'tableRow': string;
}
export const cssExports: CssExports;
export default cssExports;
