export const START_GAME = 'START_GAME';
export const PAUSE_GAME = 'PAUSE_GAME';
export const RESUME_GAME = 'RESUME_GAME';
export const END_GAME = 'END_GAME';

export const LOAD_LOCAL_DATA = 'LOAD_LOCAL_DATA';

export const LOAD_LEVEL = 'LOAD_LEVEL';
export const RESET_LEVEL = 'RESET_LEVEL';
export const END_LEVEL = 'END_LEVEL';

export const CHANGE_CARD_STATUS = 'CHANGE_CARD_STATUS';
export const CHANGE_PAUSE_STATUS = 'CHANGE_PAUSE_STATUS';
export const CHANGE_VOLUME = 'CHANGE_VOLUME';
export const CHANGE_HOTKEY = 'CHANGE_HOTKEY';
export const CHANGE_GAME_LEVELS = 'CHANGE_GAME_LEVELS';
export const CHANGE_BG_COLOR = 'CHANGE_BG_COLOR';
export const SET_DEFAULT_SETTINGS = 'SET_DEFAULT_SETTINGS';