export const START_GAME = 'START_GAME';
export const END_GAME = 'END_GAME';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const LOAD_LOCAL_GAME_DATA = 'LOAD_LOCAL_GAME_DATA';
export const LOAD_LOCAL_SETTINGS_DATA = 'LOAD_LOCAL_SETTINGS_DATA';

export const LOAD_LEVEL = 'LOAD_LEVEL';
export const SAVE_SCORE = 'SAVE_SCORE';

export const AUTOPLAY = 'AUTOPLAY';

export const CHANGE_CARD_STATUS = 'CHANGE_CARD_STATUS';
export const CHANGE_PAUSE_STATUS = 'CHANGE_PAUSE_STATUS';
export const CHANGE_VOLUME = 'CHANGE_VOLUME';
export const CHANGE_HOTKEY = 'CHANGE_HOTKEY';
export const CHANGE_BG_COLOR = 'CHANGE_BG_COLOR';
export const TOGGLE_PATTERN = 'TOGGLE_PATTERN';
export const SET_DEFAULT_SETTINGS = 'SET_DEFAULT_SETTINGS';
