// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonGroup': string;
  'divider': string;
  'gameControls': string;
}
export const cssExports: CssExports;
export default cssExports;
