// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonGroup': string;
  'danger': string;
  'dark': string;
  'helperText': string;
  'input': string;
  'inputContainer': string;
  'light': string;
  'loginButton': string;
  'loginContainer': string;
  'separator': string;
}
export const cssExports: CssExports;
export default cssExports;
