// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'NameInput': string;
  'footer': string;
  'helperText': string;
  'input': string;
  'inputContainer': string;
  'inputDanger': string;
  'menu': string;
}
export const cssExports: CssExports;
export default cssExports;
