// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Card': string;
  'CardColor': string;
  'CardCover': string;
  'appear': string;
  'closed': string;
  'opened': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
