// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appear': string;
  'card': string;
  'cardColor': string;
  'cardCover': string;
  'cardOpened': string;
  'pattern': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
