// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'dark': string;
  'input': string;
  'inputContainer': string;
  'light': string;
  'table': string;
  'tableRow': string;
}
export const cssExports: CssExports;
export default cssExports;
