// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Settings': string;
  'buttonWrapper': string;
  'input': string;
  'inputContainer': string;
  'settingsElement': string;
}
export const cssExports: CssExports;
export default cssExports;
