// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonWrapper': string;
  'dark': string;
  'input': string;
  'inputContainer': string;
  'light': string;
  'settings': string;
  'settingsElement': string;
}
export const cssExports: CssExports;
export default cssExports;
