// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Header': string;
  'button': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
