// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appear': string;
  'card': string;
  'cardCover': string;
  'cardFace': string;
  'dark': string;
  'light': string;
  'opened': string;
  'pattern': string;
}
export const cssExports: CssExports;
export default cssExports;
