// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonText': string;
  'dark': string;
  'light': string;
}
export const cssExports: CssExports;
export default cssExports;
