// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'loginButton': string;
  'loginContainer': string;
  'menu': string;
  'playerName': string;
  'separator': string;
}
export const cssExports: CssExports;
export default cssExports;
